version: '3'
# TODO make volume as internal db in container
services:
  mongo:
    container_name: mongo
    image: mongo:4
    command: --replSet rs0
    ports:
      - '27017:27017'
      - '28017:28017'
    volumes:
      - ./mongo/mongo:/data/db